using Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Entities.Models
{
    public class DeliveryClientOrganization: Institution
    {
        public DeliveryClientOrgType DeliveryClientOrgType { get; set; }
        public int OrganizationActivityId { get; set; }
        public int AvgDailyOrders { get; set; }
        public int AvgMonthlyOrders { get; set; }
        public int SerialNumber { get; set; } //auto generated by sql 

        public OrganizationActivity OrganizationActivity { get; set; }
        public ICollection<DeliveryClientOrgProduct> DeliveryClientOrgProducts { get; set; }
        public ICollection<DeliveryClientUser> DeliveryClientUsers  { get; set; }
    }
}
